### ISSUE TITLE
GPIO access through sysfs/gpiod does not work

### ISSUE THREAD

**Issue by edgar-bonet** [RedPitaya/RedPitaya#307]
According to the [Red Pitaya documentation on GPIOs][doc], pins `DIO[0-7]_{P,N}` on the extension connector E1 are user-accessible through the Linux sysfs interface, which identifies pin `DIO0_P` as “gpio968”. This does not seem to work on my “125-14 4-input” board. As an input, this pin always reads `0`, irrespective of how I drive it:

```shell
$ echo 968 > /sys/class/gpio/export
$ cat /sys/class/gpio/gpio968/direction
in
$ # Now I connect pin DIO0_P to GND, then
$ cat /sys/class/gpio/gpio968/value
0
$ # Now I connect pin DIO0_P to 3V3, then
$ cat /sys/class/gpio/gpio968/value
0
$ echo 968 > /sys/class/gpio/unexport
```

I also tried with the character device interface (`gpioget gpiochip0 62`) with identical results. I then tried a few other pins: some read always `0`, some read always `1`, none cares about how it is being externally driven.

System information (from `/tmp/sysinfo.json`):

```yaml
model: STEM_125-14_Z7020_4IN_v1.3
mac: 00:26:32:F0:B4:6D
dna: 0044ccc01d09685c
ecosystem:
  name: Ecosystem
  version: 2.00-35
  revision: aff683518
  description: Red Pitaya GNU/Linux OS & Ecosystem.
  linux_ver: '2.04'
linux: '2.04'
mem_size: '461'
mem_upgrade: '0'
boot_512: '1'
fpga:
  barebones: fc937aaf2
  logic: fc937aaf2
  stream_app: fc937aaf2
  v0.94: fc937aaf2
```

[doc]: https://redpitaya.readthedocs.io/en/latest/developerGuide/software/other_info/gpio/gpio.html#sysfs-access
